/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "stm32f446xx.h"
#include "stdio.h"
#define LOW 0
#define BTN_PRESSED LOW

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(void)
{
	for(uint32_t i =0;i < 100000;i++);
}

int main(void)
{
	GPIO_Handle_t GpioBtn;
	//GpioLed.pGPIOx = GPIOA;
	//GpioLed.GPIO_PinConfig_t.GPIO_PinNumber = GPIO_PIN_NO_5;
	//GpioLed.GPIO_PinConfig_t.GPIO_PinMode = GPIO_MODE_OUT;
	//GpioLed.GPIO_PinConfig_t.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	//GpioLed.GPIO_PinConfig_t.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	//GpioLed.GPIO_PinConfig_t.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	//GPIO_PeriClockControl(GPIOA, ENABLE);

	//GPIO_Init(&GpioLed);

	GPIO_PinSetup(GPIOA, 5, OUTPUT, HIGH, PP, PUSHDOWN);

	GpioBtn.pGPIOx = GPIOC;
	GpioBtn.GPIO_PinConfig_t.GPIO_PinNumber = GPIO_PIN_NO_13;
	GpioBtn.GPIO_PinConfig_t.GPIO_PinMode = GPIO_MODE_IN;
	GpioBtn.GPIO_PinConfig_t.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	GpioBtn.GPIO_PinConfig_t.GPIO_PinPuPdControl = GPIO_PIN_PU;

	GPIO_PeriClockControl(GPIOC, ENABLE);

	GPIO_Init(&GpioBtn);

	//GPIO_PinSetup(GPIOC, 13, INPUT, HIGH, NO_PUPD);

	uint8_t state = 0;

	while(1){
		if(GPIO_ReadFromInputPin(GPIOC,GPIO_PIN_NO_13) == BTN_PRESSED)
				{
					//delay();
					//GPIO_ToggleOutputPin(GPIOA,GPIO_PIN_NO_5);
					if(state == 0){
					printf("Button Pressed\n");
					state = 1;
					}
					GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_5, 1);
				}
		else
		{
			state = 0;
			GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_5, 0);
		}
	}




	for(;;);
}
